KEYWORD_GROUPS = {
    "Records & Document Management": [
        "electronic document management system",
        "document management system",
        "document management software",
        "edms",
        "dms",
        "enterprise content management",
        "ecm",
        "content services platform",
        "content management system",
        "cms platform",
        "records management system",
        "electronic records management system",
        "erms",
        "records information system",
        "registry management system",
        "file registry system",
        "file tracking system",
        "document tracking system",
        "government registry system",
        "records digitization",
        "document digitization",
        "scanning and archiving",
        "electronic archiving system",
        "archives management system",
        "digital archives",
        "records centre system",
        "information repository",
        "knowledge repository",
        "retention and disposal system",
        "document lifecycle management",
        "information governance",
        "records retention",
        "document capture",
        "optical character recognition",
        "ocr system",
        "intelligent document processing",
        "document automation",
        "paperless office",
        "digital transformation",
        "document workflow",
        "version control system",
        "document collaboration",
        "sharepoint alternative",
        "cloud document management",
    ],
    "Case & Complaint Management": [
        "case management system",
        "case management software",
        "case handling system",
        "case tracking system",
        "matter management system",
        "correspondence management system",
        "correspondence tracking",
        "inward and outward correspondence system",
        "mail management system",
        "docket management system",
        "complaint management system",
        "complaint tracking",
        "grievance redress mechanism",
        "grm system",
        "complaints and case handling system",
        "service request management system",
        "service request tracking",
        "service desk system",
        "help desk software",
        "ticketing system",
        "issue tracking system",
        "customer relationship management",
        "crm system",
        "citizen engagement platform",
        "public grievance system",
        "feedback management system",
        "incident management system",
        "inquiry management",
        "queue management system",
    ],
    "Workflow & Process Management": [
        "workflow management system",
        "workflow automation",
        "workflow software",
        "business process management",
        "bpm system",
        "bpm software",
        "process automation system",
        "digital workflow solution",
        "task management system",
        "approval workflow",
        "process orchestration",
        "robotic process automation",
        "rpa system",
        "low code platform",
        "no code platform",
        "workflow engine",
        "process optimization",
        "business process automation",
        "operational workflow",
        "enterprise automation",
    ],
    "E-Government & Digital Services": [
        "e-government platform",
        "digital government platform",
        "digital government solution",
        "government information management system",
        "public sector information system",
        "digital public service platform",
        "government workflow system",
        "e-governance platform",
        "citizen portal",
        "government portal",
        "public service delivery platform",
        "digital service platform",
        "government automation",
        "public sector digitization",
        "smart government",
        "government cloud platform",
        "g-cloud",
        "government as a platform",
        "digital infrastructure",
        "interoperability platform",
        "government integration platform",
    ],
    "Contract & Procurement Systems": [
        "contract management system",
        "contract management software",
        "contract lifecycle management",
        "clm system",
        "procurement records system",
        "procurement management system",
        "tender management system",
        "e-procurement records",
        "e-procurement platform",
        "supplier management system",
        "vendor management system",
        "purchase order system",
        "sourcing platform",
        "spend management",
        "procurement automation",
        "contract repository",
        "agreement management",
    ],
    "Legal & Compliance Systems": [
        "legal case management system",
        "legal document management",
        "legal matter management",
        "compliance management system",
        "regulatory compliance software",
        "audit management system",
        "policy management system",
        "legal workflow automation",
        "litigation management",
        "legal operations platform",
        "court management system",
        "judicial case management",
        "law practice management",
    ],
    "Data & Information Management": [
        "data management system",
        "master data management",
        "mdm system",
        "data governance platform",
        "metadata management",
        "information management system",
        "data catalog",
        "data warehouse",
        "business intelligence",
        "bi system",
        "analytics platform",
        "reporting system",
        "dashboard solution",
        "data integration platform",
        "etl system",
        "data quality management",
    ],
    "Collaboration & Communication": [
        "collaboration platform",
        "team collaboration software",
        "enterprise collaboration",
        "unified communication",
        "video conferencing system",
        "project management software",
        "project collaboration",
        "shared workspace",
        "intranet platform",
        "employee portal",
        "knowledge management system",
        "wiki platform",
        "discussion forum",
        "enterprise social network",
    ],
    "Security & Access Management": [
        "identity management system",
        "access control system",
        "identity and access management",
        "iam system",
        "single sign-on",
        "sso solution",
        "authentication system",
        "authorization platform",
        "privileged access management",
        "security information system",
        "cybersecurity platform",
        "data security software",
        "encryption system",
        "digital signature solution",
    ],
    "ICT Infrastructure & Platforms": [
        "cloud infrastructure",
        "cloud platform",
        "cloud migration",
        "server infrastructure",
        "data center solution",
        "virtualization platform",
        "container platform",
        "kubernetes",
        "devops platform",
        "it service management",
        "itsm platform",
        "it asset management",
        "network management system",
        "monitoring system",
        "it operations platform",
    ],
}

ALL_KEYWORDS = sorted(
    {kw.lower() for group in KEYWORD_GROUPS.values() for kw in group}
)