KEYWORD_GROUPS = {
    "Case & Complaint Management": [
        "case management system",
        "case management software",
        "case handling system",
        "correspondence management system",
        "case tracking system",
        "matter management system",
        "complaints handling system",
        "complaint management system",
        "grievance redress system",
        "grievance management system",
        "dispute management system",
        "service request management",
        "citizen complaint system",
        "public complaint management",
        "complaint tracking system",
        "issue tracking system",
        "resolution management",
    ],
    "Records & Document Management": [
        "records management system",
        "records information management system",
        "electronic records management system",
        "document records management",
        "archives management system",
        "archival management system",
        "file tracking system",
        "file registry system",
        "registry management system",
        "document management system",
        "electronic document management system",
        "edms",
        "enterprise content management",
        "ecm system",
        "content management platform",
        "records digitization",
        "digital records system",
        "electronic archiving system",
        "document imaging system",
        "scanning and digitization",
        "information repository",
        "document repository system",
        "records retention system",
        "file management system",
    ],
    "Workflow & Process Management": [
        "workflow management system",
        "workflow automation platform",
        "business process management system",
        "bpm system",
        "process automation platform",
        "digital workflow system",
        "automated workflow",
        "process management software",
        "task management system",
        "approval workflow system",
        "routing system",
        "process tracking system",
    ],
    "E-Government & Digital Transformation": [
        "e-government platform",
        "e-government system",
        "digital government platform",
        "digital government solution",
        "government digitalization",
        "digital transformation",
        "e-services platform",
        "citizen services platform",
        "public service delivery",
        "government automation",
        "public sector digitization",
        "smart government",
        "government cloud platform",
        "integrated government system",
        "interoperability platform",
    ],
    "Citizen & Public Services": [
        "citizen portal",
        "citizen services portal",
        "service delivery portal",
        "public portal",
        "licensing management system",
        "permit management system",
        "license issuance system",
        "registration system",
        "application management system",
        "public inquiry system",
        "citizen engagement platform",
        "self-service portal",
    ],
    "Enterprise Information Systems": [
        "enterprise information system",
        "information management platform",
        "knowledge management system",
        "data management system",
        "integrated management system",
        "governance platform",
        "compliance management system",
        "audit trail system",
        "metadata management",
        "information governance",
        "data governance platform",
    ],
    "Specialized Government Systems": [
        "land management system",
        "property registration system",
        "tax administration system",
        "revenue management system",
        "municipal services system",
        "local government system",
        "ministry automation",
        "department management system",
        "regulatory compliance system",
        "public sector erp",
        "government resource planning",
    ],
}

ALL_KEYWORDS = sorted(
    {kw.lower() for group in KEYWORD_GROUPS.values() for kw in group}
)
