KEYWORD_GROUPS = {
    "Case & Complaint Management": [
        "case management",
        "case handling",
        "correspondence management",
        "case tracking system",
        "matter management system",
        "complaints & case handling",
        "complaint management system",
        "grievance redress system",
        "grievance handling",
        "dispute management system",
        "service request system",
        "service desk software",
        "help desk software",
        "docket management",
    ],
    "Records & Document Management": [
        "records management",
        "records information system",
        "records information management",
        "electronic records management",
        "records digitization",
        "archives management",
        "archival system",
        "file tracking system",
        "file registry system",
        "registry management",
        "document tracking",
        "document management system",
        "dms",
        "electronic document management system",
        "edms",
        "enterprise content management",
        "ecm",
        "electronic content management",
        "enterprise records system",
        "records centre",
        "scanning and archiving",
        "digitization of records",
        "electronic archiving",
        "document imaging",
        "e-archiving",
        "information repository",
        "document repository",
    ],
    "Workflow & Process Management": [
        "workflow system",
        "workflow automation",
        "workflow management system",
        "business process management",
        "bpm",
        "process automation system",
        "e-filing system",
        "digital filing system",
    ],
    "E-Government & Digital Services": [
        "e-government platform",
        "digital government platform",
        "e-services portal",
        "citizen services portal",
        "citizen portal",
        "service delivery portal",
        "public service portal",
        "licensing system",
        "permit management system",
        "online licensing",
        "online permits",
    ],
    "Procurement & Contract Management": [
        "contract management system",
        "contract lifecycle management",
        "procurement records system",
        "procurement management system",
        "e-procurement records",
        "tender management system",
    ],
    "Information & Content Management": [
        "information management system",
        "content services platform",
        "cms",
        "knowledge management system",
        "knowledge repository",
    ],
}

ALL_KEYWORDS = sorted(
    {kw.lower() for group in KEYWORD_GROUPS.values() for kw in group}
)
